version: '3.8'

services:
  # Frontend - Next.js Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - curagenie-network

  # Backend - FastAPI Application
  backend:
    build:
      context: ./curagenie-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./curagenie.db
      - SECRET_KEY=your-secret-key-here
      - CORS_ORIGINS=http://localhost:3000,http://frontend:3000
      - DEBUG=false
    volumes:
      - backend_uploads:/app/uploads
      - backend_models:/app/models
      - backend_db:/app/db
    networks:
      - curagenie-network

  # Redis for ML processing queues (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - curagenie-network
    restart: unless-stopped

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - curagenie-network
    restart: unless-stopped

volumes:
  backend_uploads:
    driver: local
  backend_models:
    driver: local
  backend_db:
    driver: local
  redis_data:
    driver: local

networks:
  curagenie-network:
    driver: bridge
